In [1]:
import numpy as np
import pandas as ps

In [2]:
df = ps.read_csv('fashion-mnist_train.csv')
df

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0          2       0       0       0       0       0       0       0       0   
1          9       0       0       0       0       0       0       0       0   
2          6       0       0       0       0       0       0       0       5   
3          0       0       0       0       1       2       0       0       0   
4          3       0       0       0       0       0       0       0       0   
5          4       0       0       0       5       4       5       5       3   
6          4       0       0       0       0       0       0       0       0   
7          5       0       0       0       0       0       0       0       0   
8          4       0       0       0       0       0       0       3       2   
9          8       0       0       0       0       0       0       0       0   
10         0       0       0       0       0       1       0       0       0   
11         8       0       0       0       0       0       0       0       0   
12         9       0       0       0       0       0       0       0       0   
13         0       0       0       0       0       0       0       0       0   
14         2       0       0       0       0       1       1       0       0   
15         2       0       0       0       0       0       0       0       0   
16         9       0       0       0       0       0       0       0       0   
17         3       0       0       0       0       0       0       0       0   
18         3       0       0       0       0       0       0       0       0   
19         3       0       0       0       0       0       0       0       0   
20         8       0       0       0       0       0       0       0       0   
21         7       0       0       0       0       0       0       0       0   
22         4       0       0       0       0       0       0       0       0   
23         4       0       0       0       0       0       1       0       1   
24         0       0       0       0       0       0       0       0       0   
25         4       0       0       0       0       2       0       0       0   
26         4       0       0       0       0       0       0       0       1   
27         8       0       0       0       0       0       0       0       1   
28         7       0       0       0       0       0       0       0       0   
29         1       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
59970      7       0       0       0       0       0       0       0       0   
59971      5       0       0       0       0       0       0       0       0   
59972      2       0       0       0       0       0       0       0       0   
59973      8       0       0       0       0       0       0       0       0   
59974      7       0       0       0       0       0       0       0       0   
59975      9       0       0       0       0       0       0       0       0   
59976      5       0       0       0       0       0       0       0       0   
59977      8       0       0       0       0       0       0       0       0   
59978      6       0       0       0       0       0       0       0       0   
59979      5       0       0       0       0       0       0       0       0   
59980      0       0       0       0       2       0       0       0       0   
59981      5       0       0       0       0       0       0       0       0   
59982      5       0       0       0       0       0       0       0       0   
59983      5       0       0       0       0       0       0       0       0   
59984      7       0       0       0       0       0       0       0       0   
59985      6       0       0       0       0       0       0       0       0   
59986      6       0       0       0       0       0       0       0       0   
59987      5       0       0       0       0       0       0       0       0   
59988  

In [3]:
y = df['label'].as_matrix()
y = np.reshape(y,(len(y),1))

df = df.drop(['label'], axis = 1)
x = df.as_matrix() / 255

C:\Users\Cordu\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.
C:\Users\Cordu\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """


In [4]:
from keras.utils import np_utils
y = np_utils.to_categorical(y, num_classes=10)
print(y)

Using TensorFlow backend.


[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def d_sigmoid(x):
    return sigmoid(x) * (1 - sigmoid(x))

In [6]:
def learn():
    iterations = 10000
    learning_rate = 0.0001
    w1 = np.random.randn(784,15)
    w2 = np.random.randn(15,10)
    for i in range(iterations):
        # Forward propagation
        z1 = np.dot(x, w1)
        a1 = sigmoid(z1)
        z2 = np.dot(a1, w2)
        a2 = sigmoid(z2)
        
        # Loss (crossentropy se potriveste mai bine)
        
        error = np.sum((a2 - y) * (a2 - y))
        
        # Back propagation
        
        derror_da2 = a2 - y
        da2_dz2 = d_sigmoid(z2)
        dz2_da1 = w2
        dz2_dw2 = a1
        da1_dz1 = d_sigmoid(z1)
        dz1_dw1 = x
        
        derror_dw2 = np.dot(dz2_dw2.T, derror_da2 * da2_dz2)
        derror_dw1 = np.dot(dz1_dw1.T, np.dot(derror_da2 * da2_dz2, dz2_da1.T) * da1_dz1)
        
        w2 -= learning_rate * derror_dw2
        w1 -= learning_rate * derror_dw1
        
        if i % 100 == 1:
            print(error)
    return w1,w2

In [7]:
w1, w2 = learn()

96411.90713131322
42553.17391280299
34746.59415373816
29636.95804861884
26109.119124857643
24580.4304755118
23674.65025902672
23041.418510089337
22552.9666909999
22152.28501774632
21813.80632362672
21521.506642425273
21261.342875113227
21021.368745401065
20788.31048052102
20553.48249428545
20322.65010311478
20071.670820711443
19604.181370486956
19054.32603133271
18460.510494054743
17801.45267567334
17223.068856168098
16818.22099703379
16505.927766523735
16245.691788508511
16020.070183684802
15820.712016481575
15644.621357345863
15487.941389072814
15346.41201046492
15216.873980837569
15097.254935931374
14986.210285317877
14882.195353425652
14783.258240694182
14687.944938663062
14596.40000474473
14509.224523412155
14427.264962873685
14349.97305199164
14276.683605817805
14206.664950582093
14139.36011203012
14074.522635665855
14012.024084596576
13951.670371891725
13893.182624203811
13836.250453092935
13780.645530322705
13726.34043996285
13673.451587002135
13622.055580635591
13572.073585658